version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-nerdstore
        environment:
            RABBITMQ_DEFAULT_USER: "nerdstore"
            RABBITMQ_DEFAULT_PASS: "nerdstore"
            
    sql-server:
        image: desenvolvedor/nerdstore-sql-server:latest
        container_name: nerdstore-sql-server
        build:
            context: ../sql
            dockerfile: ./Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"

    web-mvc:
        image: desenvolvedorio/nerdstore-web-mvc-ecommerce:latest
        container_name: nerdstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
        ports:
            - "5001:5001"
        environment:    
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
        depends_on:
            - api-catalogo

    api-identidade:
        image: desenvolvedorio/nerdstore-api-identidade:latest
        container_name: nerdstore-api-identidade    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Identidade.API/Dockerfile   
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5101
        depends_on:
            - rabbitmq
            - sql-server

    api-carrinho:
        image: desenvolvedorio/nerdstore-api-carrinho:latest
        container_name: nerdstore-api-carrinho
        build: 
            context: ../src
            dockerfile: ./services/NSE.Carrinho.API/Dockerfile                
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5201
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server  

    api-catalogo:
        image: desenvolvedorio/nerdstore-api-catalogo:latest
        container_name: nerdstore-api-catalogo
        build:
            context: ../src
            dockerfile: ./services/NSE.Catalogo.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5301
        depends_on:
            - rabbitmq
            - sql-server

    api-cliente:
        image: desenvolvedorio/nerdstore-api-cliente:latest
        container_name: nerdstore-api-cliente    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Cliente.API/Dockerfile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5401
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server  

    api-bff-compras:
        image: desenvolvedorio/nerdstore-api-bff-compras:latest
        container_name: nerdstore-api-bff-compras
        build: 
            context: ../src
            dockerfile: ./api gateway/NSE.BFF.Compras/Dockerfile  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5501
        depends_on:
            - rabbitmq
            - api-identidade
            - api-carrinho
            - api-pagamento
            - api-pedido
            
    api-pagamento:
        image: desenvolvedorio/nerdstore-api-pagamento:latest
        container_name: nerdstore-api-pagamento    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Pagamento.API/Dockerfile   
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5601
        depends_on:
            - rabbitmq
            - api-identidade
            - api-pedido
            - sql-server
            
    api-pedido:
        image: desenvolvedorio/nerdstore-api-pedido:latest
        container_name: nerdstore-api-pedido    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Pedidos.API/Dockerfile             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:57012
        depends_on:
            - rabbitmq
            - sql-server
            - api-identidade                    