version: "3"

services:



    sql-server:
        image: desenvolvedorio/nerdstore-sql-server:latest
        container_name: nerdstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y" 
        ports:
            - "1433:1433"    
